apiVersion: "v1"
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
    - name: web
      image: <your_image_tag>/webapp
      ports:
        - containerPort: 5000
          protocol: TCP
